### ISSUE TITLE
兄弟，你这代码我难受好几天了。。。。。

### ISSUE THREAD

**Issue by shangzhensen** [MenglinLu/Chinese-clinical-NER#8]
为什么bert代码，预测的时候一直报这个错。。。
TypeError: Tensors in list passed to 'values' of 'ConcatV2' Op have types [bool, float32] that don't all match.

最后一次生成的列表中的张量一个是bool，一个是float，为什么会这样，导致我跑不起来，能帮我解决一下吗。

**Comment by MenglinLu** [comment]
是在哪个文件

**Comment by shangzhensen** [comment]
兄弟，我都不用你的代码的，狗几把不是。

**Comment by deskl0** [comment]
你可以试一下用keras2.4.0
